backend:
  name: github
  repo: MaudL/cookbook-gatsby
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "recipes"
    label: "Recettes"
    folder: "src/pages/recipes"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "recipe-post",
        }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Source", name: "source", widget: "string", required: false }
      - { label: "Image (Please compress it)", name: "image", choose_url: false, widget: "image" }
      - { label: "Durée", name: "duration", widget: "string" }
      - { label: "Nombre de personnes", name: "servings", widget: "number" }
      - { label: "Ingrédients", name: "ingredients", widget: "ingredients" }
      - {
          label: "Sous recettes",
          name: "subRecipes",
          widget: "list",
          fields:
            [
              { label: "Titre", name: "title", widget: "string" },
              { label: "Ingrédients", name: "ingredients", widget: "ingredients" },
            ],
        }
      - { label: "Recette", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Accueil"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Titre, name: title, widget: string }
          - { label: Image, name: image, widget: image }
